### ISSUE TITLE
Make Currency IDs, UUIDs.

### ISSUE THREAD

**Issue by Articdive** [lokka30/Treasury#1]
Make the Currency ID an UUID, it fits better into the Minecraft Plugin world.

**Comment by lokka30** [comment]
> 
> 
> Make the Currency ID an UUID, it fits better into the Minecraft Plugin world.

Thanks for the suggestion Arctic! - although I disagree (currently). I truly hope you can convince me otherwise since I am very interested in your suggestion.

Currency ID represents a name of a currency, such as `dollars`, `tokens` or something.
By using names of currencies as their IDs, it allows balances to be transferred across different economy providers through the migrate command (`/treasury migrate`) since it can just detect if the Provider being transferred to has the same currency/currencies as the Provider being transferred from. [Here](https://github.com/lokka30/Treasury/blob/master/src/main/java/me/lokka30/treasury/plugin/command/treasury/subcommand/MigrateSubcommand.java#L115) is the code I am talking about.

I don't actually see why we should use UUIDs. It should be impossible to conflict since the economy provider handles which currencies exist. However, there is one thing I can think of now which is that if you wanted to rename a currency, all the old balances would disappear.

What do you think? :)

**Comment by Articdive** [comment]
I think that the main key for Currencies should be UUIDs, maybe I want to be able to rename my Currency later on, it's purely a background thing, people should always see the "CurrencyName" and there should be a Map from "CurrencyName" --> CurrencyObject for plugins that need it, However, **internally it should be stored with a UUID** so that the database has a (unique) "primary index" later on and you can rename Currencies.

**Comment by lokka30** [comment]
> 
> 
> I think that the main key for Currencies should be UUIDs, maybe I want to be able to rename my Currency later on, it's purely a background thing, people should always see the "CurrencyName" and there should be a Map from "CurrencyName" --> CurrencyObject for plugins that need it, However, **internally it should be stored with a UUID** so that the database has a (unique) "primary index" later on and you can rename Currencies.

Brilliant idea, thank you for the clarification. I'm all for this now.

**Comment by Articdive** [comment]
Yeah and Plugins would basically only use the "CurrencyName" to "CurrencyObject" and vice versa when talking to players, elsewhere they just store the Currency's UUID to use later.

**Comment by lokka30** [comment]
@Articdive I've added this in the latest commit. Does it satisfy your suggestion? :)

**Comment by Articdive** [comment]
Looks good
