### ISSUE TITLE
Switch to 'Bank Permissions' system.

### ISSUE THREAD

**Issue by lokka30** [lokka30/Treasury#31]
Suggested by @MrNemo64.

See [this](https://www.spigotmc.org/threads/new-economy-api-looking-for-your-feedback.527805/page-3#post-4280097) reply on SpigotMC.

**Comment by MrNemo64** [comment]
I'm going to work on this issue (@lokka30 if you want to asign it to me I'm ok with that).
So I've thought about several ways of doing this, I'll explain them here:

1. Use an enum for permissions. Simplest way, have an enum with the permissions, something like `WITHDRAW`, `DEPOSIT`, `CONSULT`, `ADD_MEMBERS`, `REMOVE_MEMBERS`, `ADD_OWNER`, `REMOVE_OWNER`
2. Use an int for permissions. We would have an interface like [SwingConstants](https://docs.oracle.com/javase/7/docs/api/javax/swing/SwingConstants.html), this interface would have all the default permissions, since we do it with ints instead of an enum a specific provider may add custom permissions
3. Use an int for permissions with masks. We would have an interface with the default permissions and each one would be a bit of a number (f.e.: `WITHDRAW=0x01` `DEPOSIT=0x02` `CONSULT=0x04` `ADD_MEMBERS=0x08` `REMOVE_MEMBERS=0x16` `ADD_OWNER=0x32` `REMOVE_OWNER=0x64`). The interface would also have methods like 
```Java
public static boolean isDepositSet(int premissions) {
  return (permissions & DEPOSIT) == DEPOSIT;
}
```
knowing if a player has a permission or not would use these masks, we have room for specific implementations to add custom permissions and getting all permissions from a player is just getting a number

There are the 3 options I though of, would like to get feedback

**Comment by lokka30** [comment]
@MrNemo64 
Great!
Although my opinion can be flexible if you believe option 2 or 3 are better, I believe the enum (option 1) is the best way to go. So long we plan accurately enough all the constants that people would like to use, then we should rarely have to modify the enum.
I don't know if we should facilitate custom permissions or not, as I don't see how one needs to go beyond a good set of permissions already provided by Treasury.

**Comment by MrNemo64** [comment]
> @MrNemo64 Great! Although my opinion can be flexible if you believe option 2 or 3 are better, I believe the enum (option 1) is the best way to go. So long we plan accurately enough all the constants that people would like to use, then we should rarely have to modify the enum. I don't know if we should facilitate custom permissions or not, as I don't see how one needs to go beyond a good set of permissions already provided by Treasury.

If I had to choose, I'd go with first or second option. I have a preference for the first one. If a specific provider wants custom permissions he can provide his own methods and if a plugin wants to use them he can just depend from that specific implementation. For your average plugin I only see `WITHDRAW`, `DEPOSIT`, `CONSULT`, `ADD_MEMBERS`, `REMOVE_MEMBERS`, `ADD_OWNER` and `REMOVE_OWNER` as possible options. Maybe I'm missing one but right now I can't think of more.

Would like to listen to @Jikoo @MrIvanPlays and @NoahvdAa if possible

**Comment by lokka30** [comment]
My preference for the first option is quite strong. What would the `CONSULT` permission allow for?

**Comment by MrNemo64** [comment]
> My preference for the first option is quite strong. What would the `CONSULT` permission allow for?

WITHDRAW -> Allows a player to withdraw from the bank account
DEPOSIT -> Allows a player to deposit on the bank account
CONSULT -> Allows a player check the balance on the bank account
ADD_MEMBERS -> Allows a player to add members to a bank account
REMOVE_MEMBERS -> Allows a player to remove members from a bank account
ADD_OWNERS -> Allows a player to add owners to a bank account
REMOVE_OWNERS -> Allows a player to remove owners from a bank account
At this point we need to define what a member and what an owner is on a bank account. Is a member just someone with WITHDRAW DEPOSIT and CONSULT permissions? Is an owner just a player with all permissions?

I also think we need to define what `void retrieveBalance(@NotNull Currency currency, @NotNull EconomySubscriber<Double> subscription);` does. Does the bank acount have several ammounts of different currencies? Or it just converts automatically from the used currency to the requested one using `double convertCurrency(@NotNull Currency from, @NotNull Currency to, double value)`. The docs right now don't specify it. In my opinion it should be the first one

**Comment by lokka30** [comment]
@MrNemo64 

> CONSULT -> Allows a player check the balance on the bank account

Ah, perfect. Thanks for clarifying. We can copy these descriptions straight into the javadoc for the enum when it's made.

> Does the bank account have several amounts of different currencies?

Exactly that.
