### ISSUE TITLE
Warn the server console if an implementation is using a older/newer Treasury API version

### ISSUE THREAD

**Issue by lokka30** [lokka30/Treasury#48]
We can use `ServiceRegisterEvent` to check when one has registered, then just run some logic.

**Comment by MrNemo64** [comment]
Isn't this a Bukkit specific event? This way of checking it would only work with Bukkit based servers

**Comment by MrIvanPlays** [comment]
Alert the user to downgrade treasury or make the user bug the developer of the economy provider to update it so it uses the latest treasury version. If first is selected, we would have to nuke the update checker or print out the update message in different circumstances not only if there is a new version. I think we can also abstract the economy api version specification out from the implementations.

**Comment by MrIvanPlays** [comment]
actually currently the economy api version treasury plugin specifies is not accessible via the API. so latest economy api version needs to be moved to the api module or make EconomyAPIVersion#getLatest return the last constant (because as you might know, enums are sortable) . maybe i didn't do it in the split modules pr because i thought it is an implementation detail since it was in the treasury plugin main class.

**Comment by lokka30** [comment]
> actually currently the economy api version treasury plugin specifies is not accessible via the API. so latest economy api version needs to be moved to the api module or make EconomyAPIVersion#getLatest return the last constant (because as you might know, enums are sortable) . maybe i didn't do it in the split modules pr because i thought it is an implementation detail since it was in the treasury plugin main class.

TreasuryPlugin#getAPIVersion?

**Comment by MrIvanPlays** [comment]
Core module is not an api.
